### ISSUE TITLE
Toggle neighbor and routing edge visibility per node 

### ISSUE THREAD

**Issue by bunneydude** [bunneydude/DOGE#10]
For some networks (e.g. a star overlapping a mesh) it would be nice to hide a type of edge (routing or neighbor) on a node-by-node basis. The interface could be the same as the 'mask node/edge' button though we might want a show-all button to quickly restore the view.

Branch name: dev-10-edge_visbility

**Comment by tkmaker** [comment]
Added ability to  control edge/route visibility on a per node basis and switch over to the default view. 
Cloned from develop :  f7e610654131a98b1d2341f091a2fd3cd6440472
Merged to develop:  456fe493f76ffea7a628b37a09ca31d84b0053a7
