### ISSUE TITLE
Forward packet backed on single-hop LQE

### ISSUE THREAD

**Issue by bunneydude** [bunneydude/DOGE#12]
In order to support mesh networks, the packet forwarding policy needs to take into account LQEs from the routing table and neighbor table. There currently isn't a metric for multi-hop LQE, so when comparing routing entries, the LQE of the single-hop node referenced by the routing entry will be used.

If a node happens to have both a neighbor table entry and routing table entry targeting the same destination node (e.g. a 3-node mesh), then the LQE in the neighbor entry will be compared as well.

Two reserved LQE values will be used - 255 and 0. The network update method will never write either of these values to an entry. It will force it to the next legal value (i.e. 254 or 1). Only a memory write through the application layer is allowed to set an LQE to a reserved values.

A higher LQE means a better connection, so an LQE of 255 will cause that path to be taken almost every time. An LQE of 0 'masks' a connection to other routes will be used instead.

Merge criteria: Freeze LQE updates then write different LQE values for a 3-node mesh network. Have each node blink an LED when it forwards a packet. Show the routing path changes after switching which edge has the higher LQE.

Branch name: dev-12-lqe_packet_fwd
Branched from develop: [217fd052](https://github.com/bunneydude/DOGE/commit/217fd052ce127dd77177c92c87cc2619e850f221)

**Comment by mescalan** [comment]
Planned changes:
1. network_has_neighbor will iterate through all elements and return neighbor entry with the best LQE. LQEs of 0 will be ignored.
2. network_has_route will check the neighbor table entry LQE to see if this is a valid route.

**Comment by bunneydude** [comment]
The python side should be good for testing. There's a new file, /doge/scripts/demo_grid.py, that requests a route, masks an edge, then requests the route again and shows the single-hop ID change.

**Comment by mescalan** [comment]
Working on adding a radio ID check to network_has_neighbors, network_has_routes.

**Comment by mescalan** [comment]
Finished merge with radio ID and LQE changes
