### ISSUE TITLE
cloud services integration must function with updated DogeHub core

### ISSUE THREAD

**Issue by the-daveman** [bunneydude/DOGE#15]
DogeHub has changed quite a bit recently, and all of the changes have since broken compatibility with the old cloud streaming services.
Update streaming capabilities with DogeHub so they function with the new implementation.

**Comment by the-daveman** [comment]
Branched from develop: https://github.com/bunneydude/DOGE/commit/15284648c0a4fcd93ad3e4a2df5ce856635cdba1

Merged from develop: https://github.com/bunneydude/DOGE/commit/a3bf9058932a2be1cf370163a1190360a5337db3

**Comment by bunneydude** [comment]
Merged to develop: [194631ad](https://github.com/bunneydude/DOGE/commit/194631ad8313c40b44e37360ba37a007b60503c8)
