### ISSUE TITLE
webserver_consolidation

### ISSUE THREAD

**Issue by tkmaker** [bunneydude/DOGE#3]
Consolidating angular chart and vis network node.js servers. These were separate and the vis javascript and css were embedded in the index.html. Re-structuring this so that all js code is in linux/webserver/js and css is in linux/webserver/css

**Comment by tkmaker** [comment]
Merge back to develop planned when data plotting and network UI works as it did before

**Comment by tkmaker** [comment]
Created a unified web server using the angular framework to support the vis.js graph and the chart. Verified that the UI remains the same after consolidation.

**Comment by bunneydude** [comment]
For tracking:

Branched from develop: [2e71b2cd](https://github.com/bunneydude/DOGE/commit/2e71b2cd9b9ff2934b5b8385a069e5dc4ce0c37f)

Merged to develop: [f7e61065](https://github.com/bunneydude/DOGE/commit/f7e610654131a98b1d2341f091a2fd3cd6440472)
