### ISSUE TITLE
Dropped packets on multi-hop destinations

### ISSUE THREAD

**Issue by mescalan** [bunneydude/DOGE#5]
I'm seeing dropped application packets and ACKs transmitting to multi-hop destinations. Working on a way to reliably send traffic across multiple hops.

**Comment by bunneydude** [comment]
Branched from develop: [2db09ecb](https://github.com/bunneydude/DOGE/commit/2db09ecbae2370219756055bc7728727e2c994fa)

Merged to develop: [2e71b2cd](https://github.com/bunneydude/DOGE/commit/2e71b2cd9b9ff2934b5b8385a069e5dc4ce0c37f)
